# Generated by Django 5.2.1 on 2025-05-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("mname", models.CharField(blank=True, max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=1)),
            ],
        ),
    ]
