# Generated by Django 5.2.1 on 2025-06-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_dropboxtoken_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.CharField(max_length=100)),
                ("folder_name", models.CharField(max_length=100)),
                ("channel_name", models.CharField(max_length=50)),
            ],
        ),
    ]
