# Generated by Django 5.2.1 on 2025-06-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_channel_list"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Channel_List",
        ),
    ]
