"""
Django settings for stm_sleep project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k@&^_o&%*&vggq8)x1%-w!pz79%mhtf)(pz51sj4&bso9hur=2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# DROPBOX_ACCESS_TOKEN='sl.u.AFxp8Y0oh0MIEtGRdiTxcMFQS5cMd9N_93rqleZJi5sLyCxEs-WqA4tRKhoZNJLJl1Akhar7Dh9YXjpsk_1SCdDlLAuQZGM1Ye5d4wI6RZ_0vumAH7732CxZKp2FRynGKhJtypYqwaK5i4-yjQXLglFBW_FpKjF_4Jelk1gzxDLdi_JQZsFqYkZjdgD7lReAMuk-M3NUYYSMa6F6XaDrO1ZYC5xg5AMg-JdWwTkWZcm-LVdDt1bO6Y0LpWOxtdVti8DU_cm6gFBjYrP7BKtqmpO1s-Jw6_uzuhE0OPl60mIQyENdiY0UD_kHAAxEK4VK04FasBi4M6kBVzEQPADt3ezxlCLHb_7Am0Ns1TZJrC9bfMNdYAyRHtO3IXm4Zf_om2FLs5mNhZj-sayPYBpNFw-ckvNpeAcYPxbhYS4bIR3HozugBg_WUNKzCf1uF6z7qrJP96qY6r9vE4xKZHZbw49BBGVeEDSm4LdBwr-c4nfJWbRwe0R4LbDMTw0zu5Js7fdOyZ5DlAiiVYWQMKEsnxEg_1bo_r0ohfM81DbMXvD8mP_FlUkvH1DjTB0tXmEPs8UFJ8Gwg5TVzUStaw6NqotS0X9fKS64m74HdZauUPd7i0UkisKHzUa6UAkbl9cI0aEmfRUxqGQba74pUBondI7sPapA24W7b2Qgb3xPa9TxVGAEn96IX-_9Qz7j5t47lWpD6ByMoUTx91VbEPgBjhLGJkAsRHzCtOgzH3kbho8_STZx74xEAyq-JUGwW11zy8egBzU5UwQpJJyDPhUlBHqFFt1syxoOO0D_rGDl3iZoAjE1_Y6sqhTY17l6qphMFo43A0E757TVSEjDbuCitOZeeasR_AKpdFqjHjNRmPYEOHrFvpRxRzNLYBkDLZx0tvasaXOWWo-wKHU6_buKKYQyXzrALtNABjwaXaQ8bmE0rT4Nvv88w82PON7FM_BBY_v9ib1Rs9sWyu_UhAMVjfTn1rVOEezRfy_Py91M9ykCHyawy9bwgZIb7Due2OT4kf6g1VE7ScX-aeSFhQRFpQwQbubsHeTZYNuxm0g0pYLlo1LE3-WruXMva5Vk9IQ6ju9CdOixR81Hf6GmU1T89BGrCamGAiWbbKigEaReIu8t2dTtatF4kLvSYdhyZcEy0sfbqfnSXDj0b8-QzmdPeHQDHvW46WohhTFkXL9PCV8H7y6cUxU5-VEqZjfUBNPX1non966Jlx6yl26oA122sPeh4RPLaMpbSxP2RebeiK8LZUqD4T1oCCfQGBn3znhp5v1AmHr2fyh9R0gudsXAmnGIFkFCsRHEsqt5kARWWvg_VgB6TjU5KPZgiabdunAyP5bHNTZXcYyH3AjuBy7sL7vG8z2qptO4a_G5TU6hrqQl_NMXs9nTd8E5jL2fmPQo9rSlPWiC-xgWDP0UHdegEDk_0xRCu-dAmwsFAWiWO-xeqA'
DROPBOX_ACCESS_TOKEN='sl.u.AFxUzpn-_1-MbaKJ39Xi3Fg_Voz0r7KjQQMmmD5ecPfu-Pck5Oej9FyL8_7LVEa1eOvFrm5G9mfOCBtRb3HxZlD3NwNRDrK1xnb1zfmT45cJ-lqeuyKp2Gp_rzEnRVYrZyPs3Iory5kq8a5vTBr9PXTXnlk0NO8LRtoIkaKgSXTJcvCUfZqAgHbaLS99H3IRofL1P7jW07y0wQDpDABSDYcB98210vjARnanknkhd7ftHET8gETVAWN4rA0E3JeN52RrxAnmizS9ZP5ElWwe-vZssxRB0Mv4jntumZ-ym-qm-F1OktiuZfXwoKZiELG5PYxL_zI-IPYBptXJBUHHAc3NZMH2Tor4HKeluw_Y-bYcOFIx1vOreaq-tp3KoAjwp8FGiqFQ5rs4EmA1XWnVCxlzJIPB5o2SGNGtD0EQfsGDLC8bIEhuxQ9dxhpMy-L--H9fESGVq-rEgXZQFUp7tzgRhKK0OUocz590oZTvV7G1rXiSK_d6sSSk7wLATTi9Qesv8hMKncrjAgDwhy4Rv4l6j8EpRlxLZA4bbITqQTkWi8kxyG572_5cimL8CMgS38s9HYLHSltGA_7_xH7XigB49YmhAuftu25DO_cjOiIBN8-UrO81CrtG8AtGGlpKSzCIUJ3xXimIQiEpD3mFlQergFzN6Lij5kUfZU1mKYgHNmj13Ff_soPwjL1yHzhRD0myZ5F8zMs3_y0mTsb82ZpFRVkcCFBQEiidnF3wRobxusaLs72gXtFk560vMKLSQOhJmSf6Py_zi4U7XdZ08XffkAzB10QsW2swPWv-HWJ8WQCHg1jpjZ1bOOXpPmlf1KXGFeZD_37zMN_uvbEptxT36NIdFGuYRar1ybin_k7tR5BpJ7IS2O6iS0LIrSrGZNgynjVoCcT2jFELrA1tLkOcrcmSaN28MqSr5PeVh_2qa7873ulz0zV-CKT2qwt757Xs46d915KGDMzRyfX461bq0lntIIXMOr4LpDu3cbLLN35PzC5feBzJoiDE76xBbdaj0NiESSLCVp1ebIu7ygt2WNKW5hDifIBHHQGkMg5q5aJOwM22AOEQJFyVvFK-uGZcWeDgl4YW0i-HkaXqFQ5Aewwkt4-pIwTAHg4uFiFMYbQOExF10A5HzVxdPitOzL-tBHD_fV8P4jg4PuI0RszCB__qmGyJN4c6eqgKL3Q-P6iw44WhqSjM9QTOEOmDU5KHb4wZDr1Rl-7ACRkRaf_A8iuFAeZ3uAYR-jwGBXKbX7roG5VfN9AQtxlUv9A9KuMXZ5-FsNGV7LMJ523gsqu5y3CbiFIcJPtWXtPA-2QSavVCz-4J_tB1ci52V0RKexDb2EN1eP22_ve8QLCRJmL-0KpETuYt1DJM_wUZk-aAB2u9S3kSF0u-sf6yR3ma3jx-5TBbeHKzTNJLD_Ddtd-h2w5gDXX9pN-DupLvLw29Bw'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'corsheaders',
    'rest_framework',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # move this up here
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'stm_sleep.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stm_sleep.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

# Allow cookies and session data
CORS_ALLOW_CREDENTIALS = True
# settings.py
# Or use cached_db, file, etc.
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_SECURE = False  # True only if using HTTPS
SESSION_COOKIE_HTTPONLY = True
# settings.py

# Increase max request body size to 100MB (adjust as needed)
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 * 1024 * 1024 bytes