"""
Django settings for stm_sleep project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k@&^_o&%*&vggq8)x1%-w!pz79%mhtf)(pz51sj4&bso9hur=2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DROPBOX_APP_KEY = "0yquo89flyp8svr"
DROPBOX_APP_SECRET = "vgkfv3i3sxibhr7"


# DROPBOX_ACCESS_TOKEN = 'sl.u.AFzQNPDPaWeaSntK3Z3_6Mtgs6I16NPP2TUaga4bTupGlzlnDlDphXZe9bHNsC2kcBHs_wKKjwBRu-k7sxqOcYp86Abq4zH7NidIz0CqXQjR6sQPUQxQ0G9tAnC4xcIgSdpNx30nwnlKHUomFubzPZcnx8Kd_htTtYWI_6DpvmODgZ913yJh4lUjmINVwY7VCvN3AV74-iGjUM9ipRQ5WUcvHTT-VLasE2CcOBRovbvr0Tma6tdPgz5MdD12ZlAOtqcFIO_w6tP3Xxqx9oxiAvUjlOaEgb46W_cBhntOS1yWrsmWTdRjGPYnNR7wi_Nv_TdWKsByWh0-4dRj3ZoqP1ksLgXDlY2xInA_G9_U-I9TQVkafWjaYl33v9qLe5SGqoB8tQbwLzhiZrjOBiltAdfW9Ghwu_s-62h5kkPWo2HVKQ1dfUxY2FbY404CY81HeSqacRUJEuC8pTCQd2SkXe9qB8uAyUw6LckUQMOmUBfSgxIE1Qa7lg0ITSdizoW4js26yqpsgc2-6vZTkVOjfck_io0w8Swo6bXR8zEOgVUEfJgLVYGxpM8kOHwD77NjvH0LsBkRw5GTOWlyPrxCQ68CYTBUzIHVeldpVOrCu50WHGx3ESBgJuI6jrnthbpouF_SjIhH-iYQkKXOTfc1qwU5wgd1-eCsnGcgraN_UTGilSw2dm_Qh9v-ceNgE8Uafus_D5HBdAVHE2TCrLnp-OX5rGlTW2wVI5J9yCBYwnWJXZ8v1lIEzMU0S1SIDtSLzbPNM0Gt7hY9P-uQham9JSwRPCBUxPlsaP6OnEYvkTlFOxVX-sqVAOZdpW6i3yPnRBhq0ewpnDX4WRZJj7NtgDxEMR5niJqwDhVHrUcg_nqUgiBJCajkfdC7Wejyc8mbY4sfG0rCRwOg86VmQYg-_B9oHmmrXkYV3vprDHdVUatNGT6YrdObPUmSIGHPWDlBvg5-01rOxiEm5GI3Jhjode3_zgQld4RMsOEaQbzJDqPJP-9LIRBsalyERNLJ78Q3LR2WW38LFWZ6VqdLpoE4-Ed4O0yn076tlaKTaDJyBpG_GXX6UMnybVX_-MsDrkIUo_L0MMD0OwXjjJisCCIkKhmxr3OJ0KHP3imQZYdfYlUnraFhMZ9EjjKP32PLb0Wb0bENjVO7S1kgKJBaagNUMrHSXeHTPunN-_Qg1y9o-Bs_xPT8Z5EyDDGwT--3Z1fip0cKjxDMXnKyEUdsVOD66YzUqO6ztUEnm9TAg5jlV4pg81sAOh3x3uJPGcdZJNOFToTMjj2lUnabzhTp-nGUQD25DK7m_SAV_fYtB9iN6ouWeMVCL7OZqHACVpVcMf9U5iLU8dAKhxXxIUxDJQQpk5JYU9OrTB2Rdf9vlpLaw6XvRNg4EFZIRLJyVV9T8IbTVP5fR1_Ovft75Om10fGNNkpzoyM9aHbajihjGVnDV0wnlA'



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'corsheaders',
    'rest_framework',
    'django.contrib.staticfiles',
    'members',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # move this up here
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'stm_sleep.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stm_sleep.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ]
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

# Allow cookies and session data
CORS_ALLOW_CREDENTIALS = True
# settings.py
# Or use cached_db, file, etc.
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_SECURE = False  # True only if using HTTPS
SESSION_COOKIE_HTTPONLY = True
# settings.py

# Increase max request body size to 100MB (adjust as needed)
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 * 1024 * 1024 bytes
CHUNK_SIZE = 10 * 1024 * 1024