"""
Django settings for stm_sleep project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k@&^_o&%*&vggq8)x1%-w!pz79%mhtf)(pz51sj4&bso9hur=2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# DROPBOX_ACCESS_TOKEN='sl.u.AFxp8Y0oh0MIEtGRdiTxcMFQS5cMd9N_93rqleZJi5sLyCxEs-WqA4tRKhoZNJLJl1Akhar7Dh9YXjpsk_1SCdDlLAuQZGM1Ye5d4wI6RZ_0vumAH7732CxZKp2FRynGKhJtypYqwaK5i4-yjQXLglFBW_FpKjF_4Jelk1gzxDLdi_JQZsFqYkZjdgD7lReAMuk-M3NUYYSMa6F6XaDrO1ZYC5xg5AMg-JdWwTkWZcm-LVdDt1bO6Y0LpWOxtdVti8DU_cm6gFBjYrP7BKtqmpO1s-Jw6_uzuhE0OPl60mIQyENdiY0UD_kHAAxEK4VK04FasBi4M6kBVzEQPADt3ezxlCLHb_7Am0Ns1TZJrC9bfMNdYAyRHtO3IXm4Zf_om2FLs5mNhZj-sayPYBpNFw-ckvNpeAcYPxbhYS4bIR3HozugBg_WUNKzCf1uF6z7qrJP96qY6r9vE4xKZHZbw49BBGVeEDSm4LdBwr-c4nfJWbRwe0R4LbDMTw0zu5Js7fdOyZ5DlAiiVYWQMKEsnxEg_1bo_r0ohfM81DbMXvD8mP_FlUkvH1DjTB0tXmEPs8UFJ8Gwg5TVzUStaw6NqotS0X9fKS64m74HdZauUPd7i0UkisKHzUa6UAkbl9cI0aEmfRUxqGQba74pUBondI7sPapA24W7b2Qgb3xPa9TxVGAEn96IX-_9Qz7j5t47lWpD6ByMoUTx91VbEPgBjhLGJkAsRHzCtOgzH3kbho8_STZx74xEAyq-JUGwW11zy8egBzU5UwQpJJyDPhUlBHqFFt1syxoOO0D_rGDl3iZoAjE1_Y6sqhTY17l6qphMFo43A0E757TVSEjDbuCitOZeeasR_AKpdFqjHjNRmPYEOHrFvpRxRzNLYBkDLZx0tvasaXOWWo-wKHU6_buKKYQyXzrALtNABjwaXaQ8bmE0rT4Nvv88w82PON7FM_BBY_v9ib1Rs9sWyu_UhAMVjfTn1rVOEezRfy_Py91M9ykCHyawy9bwgZIb7Due2OT4kf6g1VE7ScX-aeSFhQRFpQwQbubsHeTZYNuxm0g0pYLlo1LE3-WruXMva5Vk9IQ6ju9CdOixR81Hf6GmU1T89BGrCamGAiWbbKigEaReIu8t2dTtatF4kLvSYdhyZcEy0sfbqfnSXDj0b8-QzmdPeHQDHvW46WohhTFkXL9PCV8H7y6cUxU5-VEqZjfUBNPX1non966Jlx6yl26oA122sPeh4RPLaMpbSxP2RebeiK8LZUqD4T1oCCfQGBn3znhp5v1AmHr2fyh9R0gudsXAmnGIFkFCsRHEsqt5kARWWvg_VgB6TjU5KPZgiabdunAyP5bHNTZXcYyH3AjuBy7sL7vG8z2qptO4a_G5TU6hrqQl_NMXs9nTd8E5jL2fmPQo9rSlPWiC-xgWDP0UHdegEDk_0xRCu-dAmwsFAWiWO-xeqA'
DROPBOX_ACCESS_TOKEN='sl.u.AFxh_c9UikraIdJZAazHEnEKpk1uMCVA8Oeu8Rlt3mugJ6GoQZMR6Aw6mpr86DVBuldZLsJ-LWA0Sk_QKEcb7MJVmJwS2w6VN0OQABT0nZBkTVzi-nH4Oqlk-_J-GgBJ7qiH0YsvBqGOYBcqP20-3DfDTsw-tlnAfv_2CiYq-3GqNiAfAD7U47jwzOQvn7t6RkYJruYzfxmB4_qlSeo4WJSokzXLIByNxFtk2C8o6dj8v4aUnBnwVvP5Mh-BxmMJlA4Mx71SpAajUxIXk-cME_c7pYCI_ch0J_8H0TWRW4OLr3vdy-I3Be-g-aFboj1eTDcILZY00xRijgfB6Paa3MPCIoSA_rbZaoEDqIizErtbCRyTf28VwEbpTqGBl7C4MOb5B1jK7V7fJiL4mZd-aFdkUOHWNpdB2p2fZMcxkffDvizbS44z7tSkbgJMoE6Hv_AAobsQDfKlLSJHPnvbFqoH3LXDcc96Fp1PXZ6r4KUJLv_QQbqCHXagmjEaztCTMsT13LHSNYqQiFN1ZSlN3Y14418a4dN_oJECAnfHa2Tr3I6L-YSscRXnX-EdFBwIDrYPgycczasqQwMemeOXmOnTF9ypVtA7dmxiUM6jpOsCYSM53GNhNTgqljDrZa_e3R1oxm2vXyinHczztfBb8RCZzzlZi70Kd8D1SBD72TXjgQjqPd71LKjo2ceupOTjbIhm7WydsbcEykOZc8jgee38M9ciJx6vzvSIRK40Ihtb5XRILpf3qWu2i37ag7bhOdWr5MQ_Jmcr1PAu1BluXQpWiP5oGOGXinsdGPXBwrZ6K73x_i54xvU228iFZ6LpfrcFKKlGiTdlDlsCT-53wi1pkpZkk0ah0PLSFmjA0ux_PBikY0gQE1az1WW2UJyjPkBAwa8gFc3rqzPfH8Cv_B9bj35w9d6hwC01wdtQf7aNDG4XdPIhh4U1M15xw_GXQDBIHEm5UW4bq-4pV9qWFupKJ9vxcFAsRyfYD3nlxsqPbQGZj4neyLXuWBoFb1dcfdMDqBHYZMneZxSfm0NyJ27Q-FGYR7BXWtQyYhSeDnYd58BfYx_nVuXgNwltw8a6VL8UbxMe3h7fghkSGTXUuw-nVQsfbxLGAnPzkmTiRsnpnm4MJx-UshXbwGVY1m6ocVHmALPKKbcl1cnXko785wpduLD27MlI14rgJkiQHxJX_PxLSxWCOlZcKlq-V9pmdrNn1HZ2ITUBSynYb8o5uM4-bOg1D1jUam0e1O1AbUHzxCdK4PZw6IvtofILbd3T8l-bXhwcKrlybutM-zuqwRDvG9Gkqlv1Dm7b6aElRz10RfNJSmsXs6ZmKjkfn_QXsh-b5m6cwuYw1KeewZt3eaRG3wXA590-eLQtp0EOPIFbZjo-gdnnQQUzyG1_gaycOjC6GNkX0gmGVLN9ZFjgmnP3'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'corsheaders',
    'rest_framework',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stm_sleep.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stm_sleep.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

# Allow cookies and session data
CORS_ALLOW_CREDENTIALS = True
# settings.py
# Or use cached_db, file, etc.
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_SECURE = False  # True only if using HTTPS
SESSION_COOKIE_HTTPONLY = True
